name: Cypress Workshop CI
on: [pull_request]

jobs:
  run-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Execute static code analysis
        run: npm run lint

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          headed: true
